packages:
  # plugin core libraries, SDK and CLI
  - packages/*
  - packages/field-plugin/packages/*
  - packages/field-plugin/packages/cli/templates/*
  - packages/field-plugin/packages/lib-helpers/*
  # plugin starter templates
  # - apps/space-plugins/*
  # - apps/tool-plugins/*
  # plugin monorepo internal tools
  - tools/*
