name: 🐛 Bug Report
description: Report a bug in any of the Storyblok Plugin packages
title: "🐛 [Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        **🚨 Issues are primarily for bug reports.** For questions, feature requests, and general discussions, please use [GitHub Discussions](https://github.com/storyblok/pluginsblok/discussions) instead.

        Please provide as much detail as possible to help us investigate and fix the issue.

  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which Storyblok Plugin package is this bug related to?
      options:
        - "@storyblok/app-extension-auth"
        - "@storyblok/field-plugin"
        - "@storyblok/field-plugin-cli"
        - "Multiple packages"
        - "Other/Unknown"
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to...
        2. Click on...
        3. Scroll down to...
        4. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: code-sample
    attributes:
      label: Code Sample
      description: If applicable, add a minimal code sample that reproduces the issue
      render: javascript
      placeholder: |
        // Your code here

        // ...

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please run the following command in your project directory and paste the output:

        ```
        npx envinfo --system --npmPackages '{@storyblok/*,storyblok}' --binaries --browsers
        ```
      render: shell
      placeholder: Paste the output of the envinfo command here...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: If applicable, add any error messages or logs
      render: shell
      placeholder: Paste any error messages here...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, related issues, etc.)
      placeholder: Any additional information that might help...
