name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**/*.md"

env:
  HUSKY: 0
  NX_REJECT_UNKNOWN_LOCAL_CACHE: 0

jobs:
  build:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node

      - name: Check public packages
        run: pnpm nx run-many --target=build,lint,test,test:types --parallel=3 -p="tag:npm:public"

      - name: Check template
        run: pnpm nx run-many --target=build,lint,test,test:types --parallel=3 -p="field-plugin-js-template,field-plugin-react-template,field-plugin-vue2-template,field-plugin-vue3-template"
