# This workflow will run tests using node and then publish a package to GitHub Packages
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: [main]
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**/*.md"

env:
  HUSKY: 0
  NX_REJECT_UNKNOWN_LOCAL_CACHE: 0

jobs:
  build:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - run: corepack enable # (app-extension-auth)
      - uses: ./.github/actions/setup-node

      - name: Check
        run: pnpm nx run-many --target=build,lint,test,test:types --parallel=3 -p="tag:npm:public"
