name: 'ci-vue2-template'
on:
  push:
    paths:
      - 'packages/cli/templates/vue2/**'
      - 'packages/field-plugin/**'
jobs:
  check-if-releasing-library:
    uses: ./.github/workflows/check-if-releasing-library.yml
  build:
    needs: check-if-releasing-library
    if: ${{ needs.check-if-releasing-library.outputs.result == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22.18.0
          cache: 'yarn'
      - run: yarn install
      - run: yarn workspace field-plugin-vue2-template build
